server:
  port: 8888
spring:
  config:
    activate:
      on-profile: local, dev, prod
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotteon2/FLOWERGARDEN.CONFIG.git
          username: ${github.username}
          password: ${github.token}
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        - http://discovery-service:8761/eureka
        - http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
encrypt:
  key: ${secret}